### ISSUE TITLE
How do I choose my own NTP server?

### ISSUE THREAD

**Issue by tulpenwase** [mcer12/Nick-ESP8266#1]
Hallo mcer12,
first of all I must say the clock is the madness! Great work.
Now to my question, I would like to use my own NTP server in my network. All my devices on the network are already synchronized through it. Currently running on my router.  Is possible if so how do you do that exactly?

I have found in the IN12_DIRECT_NEW.ino the entry for the NTP server `const char* ntpServerName` there I would deposit the IP or NTP address of my router. So far so good. In the wiki you write that Arduino binary are supported. But how do I create a new firmeware that I can upload?

Or if I could wish something would be in an upcoming update a selection menu in the web interface very helpful.

**Comment by mcer12** [comment]
Hi! The easiest thing to do would be to redirect all ntp requests to your
router. I have this option in my Asus router but you can probably do it in
other routers as well by hand.

Another way would be to change the ntp server in the sketch. You can use
option to export the binary in Arduino and then you upload it to the clock.
Be aware though that if there’s any issue in the sketch and it bricks the
clock, you will have to disassemble it to get to the serial breakout. Which
is quite annoying.

so 23. 1. 2021 v 22:06 odesílatel tulpenwase <notifications@github.com>
napsal:

**Comment by tulpenwase** [comment]
Thank you very much for the answer. Unfortunately my router does not have this redirect function. So I have to either set up a new NTP server, for example on a Raspberry Pi, which can do this or I replace the sketch...i have no idea how difficult it will be.
In case I decide to use the new sketch I would be interested to understand how to do this exactly.
I edit the IN12_DIRECT_NEW.ino and export it as binary IN12_DIRECT_NEW.hex. The *.hex and only this one file I then upload under IP_ADRESS/update with Update Firmware? Then reboot and cross my fingers.
Oh, and is there anything to note about the libraries you used for the sketch? So certain versions or from whom it was offered. I had several problems in the past because I used the wrong one.

I see forward

**Comment by mcer12** [comment]
No, in arduino IDE you can open tab Project / Export compiled binary. This will compile the project and save it as .bin file in the project directory. You still have to (!!!) set the ESP options to 1MB flash + 64KB FS, 160mhz frequency. If you forget to change the flash size, it will probably brick the clock. Sadly, I don't know what versions of libraries are used there as it's been a while since I flashed it. Hopefully downloading the latest versions will work fine.

I think it would be for the best if I just add the option in firmware and you just download the binary from github and upload it :) I will try to get to it at the start of the week.

**Comment by tulpenwase** [comment]
Good evening, I'm glad you took the trouble to add the option. Thank you very much.

**Comment by mcer12** [comment]
I've added the option and fixed a bug in daylight saving. I tested it on my clock and it works OK so fingers crossed :D It accepts server address or IP. You can use the binary in sketch directory.

**Comment by tulpenwase** [comment]
Good evening,

I uploaded the binary today and it works beautifully. Immediately, after changing the NTP address detected my router and displayed the correct time. Thank you very much for the effort.

I hereby close the ticket.
