### ISSUE TITLE
Schematic, BOM and gerber differences

### ISSUE THREAD

**Issue by Xundi007** [mcer12/Nick-ESP8266#5]
Hello,

I'm impressed by this project and wish to build this clock. The IN-12 direct drive variant.
But stuck at the BOM + shared gerbers and schematic differences.

There were some which I was able to guess it, but some of them I would like to ask for clarification, just to be sure.
These are my observations:
* The schematic shows HT7333 as LDO, where in the gerbers and BOM it is AMS1117. But with the 7333 cap values.
* The LDO capacitors marked on the schematic and BOM C2 and C3. But in the gerber silkscreen, the numbers are reversed, as C3 being the tantalum cap.
* The capacitor numbers on the gerber silkscreen generally seems to be shifted, for example on the schematic the ESP-VCC C1 cap appears to be the C4 on the gerbers.
Or the C4 and C5 caps on the schematic (on the VCC of the 74HC595Ds) are C5 and C6 on the PCB.
* And on the PCB, there is another C5 for the NCH8200HV.

I would like to ask for help on these:
* On the PCB silkscreen, the resistors R2,R3,R4,R5 are near the TLP627-2. On the schematic, near the TLP627 are just R6 and R7.
On the BOM, R2-R5 are the 20K 1210 anode resistors, which obviously not fit there on the PCB.
Which values would be good for R2,R3,R4,R5 near the TLP627-2?
* The BOM R6 and R7 are 330 Ohm values, on the schematic these are just 110.
* On the PCB silkscreen, on the nixie part, there is 8 resistor marking for the anode resistors. (R1,R2,blank,blank,R3,R4,R5,R6).
On the BOM and schematic, there are just 4x 20k 1210 piece. How should I populate them? 8*10k?
* On the schematic and BOM, there is a level shifter for the WS1812 leds, but on this PCB version, there is no such thing?
* On the backside of the nixie pcb, there are 5 unmarked smd slot near the leds. On the schematic these are not mentioned.
 I guess these for the decoupling capacitors? 100nF would be good?

Thanks in advance!
Best wishes,

**Comment by mcer12** [comment]
Hi, sorry, for some reason there was an outdated shematic. I just pushed the correct schematic, please check it out. That said, this design is old and there are errors in component designators anyway. 

I was BAD at easyeda back than and the pcb and schematic is kinda all over the place.

I will be doing a redesign in the upcoming weeks which will have everything properly set up, including BOM. If you didn't order the pcb yet, I would suggest to wait for the new version. You can maky my VFD clock in the meantime which is up to standards and well documented - IV-22 is VFD equivalent of IN-12 nixie ;)
https://github.com/mcer12/Flora-ESP8266

**Comment by Xundi007** [comment]
Thank you for the quick reply!
Well, I did ordered the pcbs, but if there will be a new, redesigned version of them I will wait for it, no problem. :)
Yes, I was planning about the Flora version too, just started with the nixies because I have some of them already on hand.
I will go on some shopping spree today for vfd. :)

And lastly, I would like to thank you for making these nice, clean designs for these tubes. With modern, available components. Complete with the 3D printed case too.

**Comment by mcer12** [comment]
Regarding the differences between pcb and schematic:
| PCB | SCHEMATIC | SHOULD BE |
| ------------- | ------------- | ------------- |
| R5, R3 (near TLP627) | missing in schematic | can be ommited |
| R4, R2 (near TLP627) | R6, R7 | 200R-330R 0603 |
| C6 | C5 | 100nF 0603 |
| C5 | missing in schematic | can be ommited |
| C4  | C1  | 100nF 0603 |
| C1  | missign in schematic | can be ommited |
| C2, C3  | C3, C2 (switched) | |
| R1-R6 (top pcb) | R2-R5 | Resistors are split in two on PCB to easily combine resistance, 1206 package |

This should be all, but as I said, I would wait for the new version. The new version will have CH340 onboard for easy flashing via USB among other changes.

**Comment by Xundi007** [comment]
Thank you again, for these additional comparison too! :)
I will probably wait for the new version.
Best wishes,
