### ISSUE TITLE
board audit failed onjlpcb

### ISSUE THREAD

**Issue by Tom-Neverwinter** [mcer12/Nick-ESP8266#7]
jlcpcb.com

> Thanks for submitting your files to review in JLCPCB. We regret to inform you that your order failed during the pre-production audit process. Reasons for the audit failure can be found in your order history. Thanks! 

```
Audit failure reason:

the spacing from slot to slot and slot to board edge are too small which will cause the board broken easily,please kindly increase it to 4mm at least.
```

`Product Detail

Gerber file:
NICK-IN12_Gerber_Y5
Build Time:
3 daysBase Material:
FR-4
Layers:
2
Dimension:
99.8 mm* 71.92 mm
PCB Qty:
5
Different Design:
1
Delivery Fomat:
Single PCB
PCB Thickness:
1.6
Impedance:
no
Layer stackup:
PCB Color:
Black
Silkscreen:
White
Surface Finish:
LeadFree HASL-RoHS
Deburring/Edge rounding:
No
Outer Copper Weight:
1
Gold Fingers:
No
Flying Probe Test:
Fully Test
Castellated Holes:
no
Remove Order Number:
No
4-Wire Kelvin Test:
No
Material Type:
FR4-Standard Tg 130-140C
Paper between PCBs:
No
Appearance Quality:
IPC Class 2 Standard
Confirm Production file:
No`

**Comment by mcer12** [comment]
Hi, this design is old and other users found discrepancies in bom. Check out my flora vfd clock which is much better designed and uses lcsc components so you can have it partially assembled. I am making new design with esp32 which will be properly done with lcsc components so I suggest to wait for that. It will be compatible with the same enclosure.

**Comment by Tom-Neverwinter** [comment]
I will wait for the new board design ♥
